### ISSUE TITLE
fix critical seo issue

### ISSUE THREAD

**Issue by jellymellio** [Nacho114/swissdef-template#24]
- [ ] canonical link is different than the main page. is sd.com used or sd.ch ? right now the .com redirects to .cn but the link is for .com
- [ ] 
<img width="564" alt="image" src="https://github.com/user-attachments/assets/7f78a124-b982-4897-bfe0-b355182c7faa">

**Comment by Nacho114** [comment]
oh!! Good catch, this should be .ch. I used .ch as the canonical page, .com re-directs there. Thank you :)
